pipeline {
    agent any

    stages {
        stage('npm auditi') {
            steps {
                
                sh 'cd web'
                sh 'pwd'
                sh 'ls -lhrt'
                sh 'npm audit | tee auditReport.html'
                
                publishHTML (
                    target : [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: '.',
                        reportFiles: 'auditReport.html',
                        reportName: 'npm auditi report',
                        reportTitles: 'Reports'
                    ]
                )
                
               
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
