pipeline {
    agent any

    stages {
        stage('npm audit') {
            steps {
                
                
                dir('web') {

                    sh 'pwd'
                    sh 'ls -lhrt'
                    sh 'npm audit | tee auditReport.txt'

                    publishHTML (
                        target : [
                            allowMissing: false,
                            alwaysLinkToLastBuild: true,
                            keepAll: true,
                            reportDir: '.',
                            reportFiles: 'auditReport.txt',
                            reportName: 'npm audit report',
                            reportTitles: 'Reports'
                        ]
                    )
                
               }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
